package netpath

import (
	_ "embed"
	"fmt"
	"html/template"
	"io"
	"math"
	"strings"
	"time"
)

// world.path is the land outline of the map, generated by
// scripts/gen-worldmap.py from Natural Earth (public domain).
//
//go:embed world.path
var worldPath string

const (
	mapW      = 1000.0
	mapK      = mapW / 360 // user units per degree, equal on both axes
	mapTop    = 84.0       // latitude at y = 0
	mapBottom = -58.0
	mapH      = (mapTop - mapBottom) * mapK
)

// project maps latitude/longitude onto the map's plain equirectangular grid.
func project(lat, lon float64) (x, y float64) { return (lon + 180) * mapK, (mapTop - lat) * mapK }

var palette = []string{"#0072B2", "#D55E00", "#009E73", "#CC79A7", "#E69F00", "#56B4E9", "#7A5195"}

type hMarker struct {
	X, Y  float64
	DY    float64 // vertical label offset, so different labels at one place don't overlap
	Kind  string  // "you", "hop", "edge", "dest", "registered", "excluded"
	Label string  // text drawn next to the marker; empty for none
	Tip   string  // hover text
}

type hArc struct {
	D      string
	Dashed bool
}

type hHop struct {
	TTL                                         int
	Addr, RTT, Place, Source, Conf, Host, Notes string
	Kind                                        string // "silent", "private" or ""
}

type hPath struct {
	ID       string
	Host     string
	Dest     string
	Color    string
	Route    string
	Observed string
	Endpoint string
	Markers  []hMarker
	Arcs     []hArc
	Hops     []hHop
	Drawn    bool
}

type hPage struct {
	Generated   string
	World       string
	ViewWorld   string
	ViewZoom    string
	ZoomFactor  float64
	Paths       []hPath
	Attribution string
	Viewpoints  string
}

func arc(x1, y1, x2, y2 float64) string {
	dx, dy := x2-x1, y2-y1
	n := math.Hypot(dx, dy)
	if n < 0.5 {
		return ""
	}
	// control point off the chord, bulging towards the top of the map
	nx, ny := dy/n, -dx/n
	if ny > 0 {
		nx, ny = -nx, -ny
	}
	cx, cy := (x1+x2)/2+nx*n*0.22, (y1+y2)/2+ny*n*0.22
	return fmt.Sprintf("M%.1f %.1fQ%.1f %.1f %.1f %.1f", x1, y1, cx, cy, x2, y2)
}

type stop struct {
	X, Y       float64
	Lat, Lon   float64
	Label, Tip string
	Hops       int
}

// buildPath converts an assessed path into drawable markers and arcs.
func buildPath(i int, p Path) (hPath, [][2]float64) {
	hp := hPath{
		ID: fmt.Sprintf("route-%d", i), Host: p.Host, Dest: p.Dest.String(),
		Color: palette[i%len(palette)], Route: p.Route(), Observed: p.observed(),
		Endpoint: p.Edge.describe(),
	}
	var bounds [][2]float64 // points that define the zoomed view

	var stops []stop
	if v := p.Vantage; v != nil {
		x, y := project(v.Lat, v.Lon)
		stops = append(stops, stop{X: x, Y: y, Lat: v.Lat, Lon: v.Lon, Label: "you", Tip: "Your viewpoint: " + v.Label + " (" + vantageNote(v) + ")"})
		hp.Markers = append(hp.Markers, hMarker{X: x, Y: y, Kind: "you", Label: "you", Tip: "Your viewpoint: " + v.Label + " (" + vantageNote(v) + ")"})
		bounds = append(bounds, [2]float64{x, y})
	}

	for _, h := range p.Hops {
		if h.Class != "public" || !h.HasCoords() || h.Dest {
			continue
		}
		x, y := project(h.Lat, h.Lon)
		tip := fmt.Sprintf("hop %d: %s, %s, %.1f ms (%s, %s confidence)", h.TTL, h.IP, placeLabel(h.ISO, h.City), h.RTT, h.Source, h.Confidence)
		if h.Confidence == "low" { // located, but ruled out: show it faintly, unconnected
			hp.Markers = append(hp.Markers, hMarker{X: x, Y: y, Kind: "excluded", Tip: tip + ". Not trusted: " + strings.Join(h.Notes, "; ")})
			continue
		}
		bounds = append(bounds, [2]float64{x, y})
		if n := len(stops); n > 0 && math.Hypot(stops[n-1].X-x, stops[n-1].Y-y) < 1.2 { // same place as the previous stop
			stops[n-1].Hops++
			continue
		}
		stops = append(stops, stop{X: x, Y: y, Lat: h.Lat, Lon: h.Lon, Hops: 1, Tip: tip})
	}

	// where traffic enters the provider
	if p.Edge.Lat != 0 || p.Edge.Lon != 0 {
		x, y := project(p.Edge.Lat, p.Edge.Lon)
		kind, label := "edge", "edge"
		if p.Edge.Kind == "consistent" {
			kind, label = "dest", "destination"
		}
		hp.Markers = append(hp.Markers, hMarker{X: x, Y: y, Kind: kind, Label: label + " · " + placeLabel(p.Edge.ISO, p.Edge.City), Tip: p.Edge.Note})
		bounds = append(bounds, [2]float64{x, y})
		if n := len(stops); n == 0 || math.Hypot(stops[n-1].X-x, stops[n-1].Y-y) >= 1.2 {
			stops = append(stops, stop{X: x, Y: y})
		}
	}
	for i, s := range stops {
		if i > 0 {
			if d := arc(stops[i-1].X, stops[i-1].Y, s.X, s.Y); d != "" {
				hp.Arcs = append(hp.Arcs, hArc{D: d})
			}
		}
		if i == 0 && p.Vantage != nil {
			continue // already drawn as "you"
		}
		if s.Tip != "" && s.Label == "" {
			t := s.Tip
			if s.Hops > 1 {
				t = fmt.Sprintf("%s (and %d more hops in the same place)", t, s.Hops-1)
			}
			hp.Markers = append(hp.Markers, hMarker{X: s.X, Y: s.Y, Kind: "hop", Tip: t})
		}
	}

	// where GeoIP says the probed address is registered: context, not evidence
	if r := p.Edge.Registered; r.HasCoords() && p.Edge.Kind != "consistent" {
		x, y := project(r.Lat, r.Lon)
		hp.Markers = append(hp.Markers, hMarker{X: x, Y: y, Kind: "registered", Label: "registered · " + placeLabel(r.ISO, r.City),
			Tip: "Where GeoIP says " + p.Dest.String() + " is registered. This is not where your traffic necessarily goes."})
		if len(stops) > 0 {
			last := stops[len(stops)-1]
			if d := arc(last.X, last.Y, x, y); d != "" {
				hp.Arcs = append(hp.Arcs, hArc{D: d, Dashed: true})
			}
		}
	}
	hp.Drawn = len(hp.Markers) > 0

	for _, h := range p.Hops {
		row := hHop{TTL: h.TTL, Kind: h.Class}
		if h.Class != "silent" {
			row.Addr, row.RTT = h.IP.String(), fmt.Sprintf("%.1f ms", h.RTT)
		}
		if h.Class == "public" {
			row.Place, row.Source, row.Conf, row.Host = placeLabel(h.ISO, h.City), h.Source, h.Confidence, h.Host
			row.Notes = strings.Join(h.Notes, "; ")
			if h.Dest {
				row.Notes = strings.TrimSpace("(destination) " + row.Notes)
			}
		}
		hp.Hops = append(hp.Hops, row)
	}
	return hp, bounds
}

// zoomBox returns a viewBox around the points, padded and kept at the map's aspect ratio.
func zoomBox(pts [][2]float64) (box string, factor float64) {
	if len(pts) == 0 {
		return fmt.Sprintf("0 0 %g %.1f", mapW, mapH), 1
	}
	minX, maxX, minY, maxY := pts[0][0], pts[0][0], pts[0][1], pts[0][1]
	for _, p := range pts {
		minX, maxX = math.Min(minX, p[0]), math.Max(maxX, p[0])
		minY, maxY = math.Min(minY, p[1]), math.Max(maxY, p[1])
	}
	w, h := maxX-minX, maxY-minY
	w, h = w*1.5, h*1.5
	const minW = 50.0 // about 18 degrees of longitude
	if w < minW {
		w = minW
	}
	if h < minW*mapH/mapW {
		h = minW * mapH / mapW
	}
	if w/h < mapW/mapH { // widen to the map's aspect ratio
		w = h * mapW / mapH
	} else {
		h = w * mapH / mapW
	}
	if w > mapW {
		w, h = mapW, mapH
	}
	cx, cy := (minX+maxX)/2, (minY+maxY)/2
	x0 := math.Max(0, math.Min(cx-w/2, mapW-w))
	y0 := math.Max(0, math.Min(cy-h/2, mapH-h))
	return fmt.Sprintf("%.1f %.1f %.1f %.1f", x0, y0, w, h), mapW / w
}

// WriteHTML writes a self-contained page (no external files or scripts) with a
// world map of the paths. attribution is shown in the footer when non-empty.
func WriteHTML(w io.Writer, paths []Path, attribution string) error {
	page := hPage{
		Generated: time.Now().UTC().Format("2006-01-02 15:04 UTC"), World: worldPath,
		ViewWorld: fmt.Sprintf("0 0 %g %.1f", mapW, mapH), Attribution: attribution,
	}
	var all [][2]float64
	vps := map[string]bool{}
	for i, p := range paths {
		hp, b := buildPath(i, p)
		page.Paths = append(page.Paths, hp)
		all = append(all, b...)
		if p.Vantage != nil {
			vps[p.Vantage.Label] = true
		}
	}
	declutter(page.Paths)
	page.ViewZoom, page.ZoomFactor = zoomBox(all)
	var vl []string
	for l := range vps {
		vl = append(vl, l)
	}
	page.Viewpoints = strings.Join(vl, " / ")
	return pageTmpl.Execute(w, page)
}

var pageTmpl = template.Must(template.New("page").Funcs(template.FuncMap{
	"f1": func(f float64) string { return fmt.Sprintf("%.1f", f) },
}).Parse(pageHTML))

// declutter draws a label once when several routes share it at the same place
// (seven endpoints entering at "edge · FR Paris" need one label, not seven),
// and stacks different labels that land on the same spot. Every marker keeps
// its hover text.
func declutter(paths []hPath) {
	type cell struct{ x, y int }
	seen := map[string]bool{}
	used := map[cell]int{}
	for pi := range paths {
		for mi := range paths[pi].Markers {
			m := &paths[pi].Markers[mi]
			if m.Label == "" {
				continue
			}
			c := cell{int(m.X / 4), int(m.Y / 4)}
			key := fmt.Sprintf("%d,%d|%s", c.x, c.y, m.Label)
			if seen[key] {
				m.Label = ""
				continue
			}
			seen[key] = true
			m.DY = float64(used[c]) * 12
			used[c]++
		}
	}
}
